import React, { useState } from "react";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, ReferenceLine, AreaChart, Area } from "recharts";
import { Canvas } from '@react-three/fiber';
import { OrbitControls, OrthographicCamera } from '@react-three/drei';
import { Scene } from './HeimViewer3D';
import AiAdvisor from './AiAdvisor';
import ReactMarkdown from 'react-markdown';

export default function DetailedAnalysisModal({ isOpen, onClose, results, boltCapacityN, placedUnits = [] }) {
    const [aiReport, setAiReport] = useState('');

    if (!isOpen) return null;

    const unitCounts = placedUnits.reduce((acc, u) => {
        const key = `${u.tsmaType} ${u.kateType}`;
        acc[key] = (acc[key] || 0) + 1;
        return acc;
    }, {});
    const unitSummary = Object.entries(unitCounts).map(([type, count]) => `${count}x ${type}`).join(", ");

    const boltData = (results.bolts || [])
        .sort((a, b) => b.netTensionN - a.netTensionN)
        .slice(0, 20)
        .map((b, i) => ({
            name: `Bolt ${i+1}`,
            tension: Math.max(0, Math.round(b.netTensionN)), // Clip negative tension to 0
            shear: Math.round(b.shearN),
            capacity: boltCapacityN
        }));

    const forceData = [
        { name: "Dead Load", force: Math.round(results.deadLoadN || 0) },
        { name: "Live Load", force: Math.round(results.liveLoadN || 0) },
        { name: "Uplift (Wind)", force: Math.round(results.upliftForceN || 0) },
        { name: "Lateral", force: Math.round(results.totalLateralForceN || 0) }
    ];

    const isStable = results.netDownwardForceN > 0 && !results.bolts?.some(b => b.isFailing);

    return (
        <div className="fixed inset-0 bg-slate-900/80 z-50 flex items-center justify-center p-4 backdrop-blur-sm print:static print:bg-white print:p-0 print:block">
            <div className="bg-white rounded-xl shadow-2xl w-full max-w-[95vw] h-[95vh] flex flex-col overflow-hidden animate-in fade-in zoom-in duration-200 print:shadow-none print:w-full print:max-w-none print:h-auto print:rounded-none">
                
                {/* Formal Print Header (Hidden on screen, visible on PDF/Print) */}
                <div className="hidden print:flex flex-col mb-4 border-b-2 border-slate-800 pb-4">
                    <div className="flex justify-between items-end">
                        <div>
                            <h1 className="text-2xl font-black text-slate-900 uppercase tracking-wider">Heim Structural Analysis Report</h1>
                            <p className="text-sm text-slate-600 mt-1 font-medium">Project: Modular Building Stability Evaluation</p>
                            {results.windDirection && (
                                <p className="text-sm font-bold text-indigo-700 mt-1">Load Direction: {results.windDirection}</p>
                            )}
                        </div>
                        <div className="text-right">
                            <p className="text-sm font-bold text-slate-800">Date: {new Date().toLocaleDateString('en-GB')}</p>
                            <p className="text-xs text-slate-500 mt-1">Generated by Heim Force Analyzer</p>
                        </div>
                    </div>
                </div>

                <div className="p-4 border-b border-slate-200 flex justify-between items-center bg-slate-50 print:bg-white print:border-none print:p-0 print:mb-4">
                    <div className="flex items-center gap-4 flex-wrap">
                        <h2 className="text-xl font-bold text-slate-800 flex items-center gap-2 print:hidden">
                            <svg className="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path></svg>
                            Detailed Analysis Report
                        </h2>
                        {results.windDirection && (
                            <span className="bg-sky-100 text-sky-800 text-xs font-bold px-3 py-1 rounded-full shadow-sm flex items-center gap-1 border border-sky-200">
                                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M14 5l7 7m0 0l-7 7m7-7H3"></path></svg>
                                Wind: {results.windDirection}
                            </span>
                        )}
                        {unitSummary && (
                            <span className="bg-indigo-100 text-indigo-800 text-xs font-bold px-3 py-1 rounded-full shadow-sm flex items-center gap-1 border border-indigo-200">
                                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"></path></svg>
                                {unitSummary}
                            </span>
                        )}
                        <span className="bg-slate-200 text-slate-700 text-xs font-bold px-3 py-1 rounded-full shadow-sm border border-slate-300">
                            🔩 {results.bolts?.length || 0} Bolts
                        </span>
                        <span className="bg-blue-100 text-blue-700 text-xs font-bold px-3 py-1 rounded-full shadow-sm border border-blue-200">
                            🔗 {results.structuralConnections?.ties || 0} Top Ties
                        </span>
                        <span className="bg-red-100 text-red-700 text-xs font-bold px-3 py-1 rounded-full shadow-sm border border-red-200">
                            🏗️ {results.structuralConnections?.struts || 0} Cross Beams
                        </span>
                    </div>
                    <div className="flex gap-2 print:hidden items-center">
                        <AiAdvisor results={results} boltCapacityN={boltCapacityN} onAiResponse={setAiReport} />
                        <button onClick={() => window.print()} className="text-sm font-bold bg-blue-600 hover:bg-blue-700 text-white px-4 py-1.5 rounded-lg flex items-center gap-2 transition-colors shadow-sm">
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"></path></svg>
                            Print to PDF
                        </button>
                        <button onClick={onClose} className="text-slate-500 hover:bg-slate-200 hover:text-slate-800 w-8 h-8 rounded-full font-bold flex items-center justify-center transition-colors">X</button>
                    </div>
                </div>
                
                <div className="flex-1 flex overflow-hidden bg-slate-50/50 print:bg-white print:flex-col print:overflow-visible">
                    
                    {/* LEFT PANEL: 3D MODEL PREVIEW */}
                    <div className="w-[35%] bg-slate-900 relative border-r border-slate-300 shadow-inner flex flex-col print:w-full print:h-[400px] print:border-none print:shadow-none print:mb-6 print:rounded-xl">
                        <div className="absolute top-4 left-5 z-10 text-white/70 text-xs font-bold pointer-events-none tracking-widest bg-black/20 px-3 py-1.5 rounded-full backdrop-blur-sm border border-white/10">
                            3D STRUCTURE PREVIEW
                        </div>
                        <Canvas shadows gl={{ preserveDrawingBuffer: true }}>
                            <OrthographicCamera makeDefault position={[15, 12, 15]} zoom={35} near={-100} far={100} />
                            <OrbitControls target={[0,0,0]} autoRotate autoRotateSpeed={1.0} enablePan={false} />
                            <Scene />
                        </Canvas>
                    </div>

                    {/* RIGHT PANEL: CHARTS */}
                    <div className="w-[65%] overflow-y-auto p-4 flex flex-col gap-4 print:w-full print:overflow-visible print:p-0">
                        {aiReport && (
                            <div className="bg-gradient-to-br from-indigo-50 to-blue-50 p-5 rounded-xl border border-indigo-100 text-sm text-slate-700 leading-relaxed prose prose-indigo max-w-none shadow-sm print:bg-white print:border-slate-300 print:shadow-none print:p-0 print:text-black">
                                <ReactMarkdown>{aiReport}</ReactMarkdown>
                            </div>
                        )}
                        {/* Top Row: Forces & Stability & Connections */}
                        <div className="flex gap-4 h-[170px] print:h-auto print:flex-col">
                            {/* Structure Forces */}
                            <div className="w-[45%] bg-white p-3 rounded-xl border border-slate-200 shadow-sm flex flex-col">
                                <h3 className="text-xs font-bold text-slate-800 mb-1 flex items-center justify-between">
                                    <span>Structure Forces (N)</span>
                                    {results.windDirection && (
                                        <span className="text-[9px] bg-slate-100 text-slate-600 px-1.5 py-0.5 rounded font-mono border border-slate-200">
                                            DIR: {results.windDirection}
                                        </span>
                                    )}
                                </h3>
                                <div className="flex-1 min-h-0">
                                    <ResponsiveContainer width="100%" height="100%">
                                        <BarChart data={forceData} layout="vertical" margin={{ top: 0, right: 10, left: 40, bottom: 0 }}>
                                            <defs>
                                                <linearGradient id="colorForce" x1="0" y1="0" x2="1" y2="0">
                                                    <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.9}/>
                                                    <stop offset="95%" stopColor="#60a5fa" stopOpacity={0.9}/>
                                                </linearGradient>
                                            </defs>
                                            <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#e2e8f0" />
                                            <XAxis type="number" tick={{fontSize: 10, fill: "#64748b"}} axisLine={false} tickLine={false} />
                                            <YAxis dataKey="name" type="category" tick={{fontSize: 10, fill: "#334155", fontWeight: 600}} width={70} axisLine={false} tickLine={false} />
                                            <Tooltip cursor={{fill: "#f8fafc"}} contentStyle={{fontSize: "12px", borderRadius: "8px", border: "1px solid #e2e8f0", padding: "4px 8px"}} />
                                            <Bar dataKey="force" fill="url(#colorForce)" radius={[0, 4, 4, 0]} maxBarSize={28} barCategoryGap="20%" />
                                        </BarChart>
                                    </ResponsiveContainer>
                                </div>
                            </div>
                            
                            {/* Stability Status */}
                            <div className="w-[25%] bg-white p-3 rounded-xl border border-slate-200 shadow-sm flex flex-col justify-center items-center">
                                <h3 className="text-xs font-bold text-slate-800 mb-2 self-start">Stability</h3>
                                <div className={`w-20 h-20 rounded-full flex flex-col items-center justify-center shadow-inner border-[6px] ${isStable ? 'border-emerald-100 bg-emerald-50 text-emerald-600' : 'border-rose-100 bg-rose-50 text-rose-600'}`}>
                                    <svg className="w-7 h-7 mb-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        {isStable ? (
                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                        ) : (
                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                                        )}
                                    </svg>
                                    <span className="text-[9px] font-black">{isStable ? 'STABLE' : 'UNSTABLE'}</span>
                                </div>
                                <div className="mt-2 w-full px-1 text-center">
                                    <div className="text-[10px] font-bold text-slate-500 leading-none mb-0.5">O. Moment</div>
                                    <div className="text-xs font-black text-slate-800">{Math.round((results.overturningMomentNm || 0)/1000).toLocaleString()} kNm</div>
                                </div>
                            </div>

                            {/* Connection Forces */}
                            <div className="w-[30%] flex flex-col gap-3">
                                <div className="flex-1 bg-white p-3 rounded-xl border border-slate-200 shadow-sm flex items-center gap-3">
                                    <div className="w-8 h-8 rounded-full bg-blue-100 flex-shrink-0 flex items-center justify-center text-blue-600">
                                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1"></path></svg>
                                    </div>
                                    <div className="min-w-0 overflow-hidden">
                                        <h4 className="text-[9px] font-bold text-slate-500 uppercase truncate">Max Roof Tie</h4>
                                        <div className="text-sm font-black text-slate-800 truncate">{Math.round(results.estimatedTieForceN || 0).toLocaleString()} <span className="text-[10px] font-semibold text-slate-400">N</span></div>
                                    </div>
                                </div>
                                <div className="flex-1 bg-white p-3 rounded-xl border border-slate-200 shadow-sm flex items-center gap-3">
                                    <div className="w-8 h-8 rounded-full bg-red-100 flex-shrink-0 flex items-center justify-center text-red-600">
                                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 8h16M4 16h16"></path></svg>
                                    </div>
                                    <div className="min-w-0 overflow-hidden">
                                        <h4 className="text-[9px] font-bold text-slate-500 uppercase truncate">Max Strut</h4>
                                        <div className="text-sm font-black text-slate-800 truncate">{Math.round(results.estimatedStrutForceN || 0).toLocaleString()} <span className="text-[10px] font-semibold text-slate-400">N</span></div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm flex flex-col flex-1 print:h-auto print:shadow-none print:border-slate-300">
                            <h3 className="text-xs font-bold text-slate-800 mb-2 uppercase">Bolt Tension Analysis (Critical Top 5)</h3>
                            
                            {(() => {
                                const sortedBolts = (results.bolts || []).sort((a, b) => b.netTensionN - a.netTensionN);
                                const maxBolt = sortedBolts[0];
                                const maxTension = maxBolt ? Math.max(0, maxBolt.netTensionN) : 0;
                                const capacityPct = Math.min(100, (maxTension / boltCapacityN) * 100).toFixed(1);
                                const isMaxSafe = maxTension <= boltCapacityN;
                                const top5Bolts = sortedBolts.slice(0, 5);

                                return (
                                    <div className="flex flex-col flex-1 min-h-0 gap-4">
                                        <div className="flex gap-4 print:gap-4 shrink-0">
                                            {/* Left: Overall Health */}
                                            <div className="w-[30%] bg-slate-50 rounded-xl border border-slate-100 p-2 flex flex-col items-center justify-center text-center">
                                                <h4 className="text-[9px] font-bold text-slate-400 mb-1 tracking-wider">WORST-CASE</h4>
                                                
                                                <div className="relative w-20 h-20 mb-2">
                                                    <svg viewBox="0 0 36 36" className="w-full h-full -rotate-90">
                                                        <path className="text-slate-200" strokeWidth="4" stroke="currentColor" fill="none"
                                                        d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
                                                        <path className={isMaxSafe ? 'text-amber-500' : 'text-red-500'} strokeWidth="4" strokeDasharray={`${capacityPct}, 100`} stroke="currentColor" fill="none"
                                                        d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
                                                    </svg>
                                                    <div className="absolute inset-0 flex flex-col items-center justify-center">
                                                        <span className={`text-lg font-black ${isMaxSafe ? 'text-slate-800' : 'text-red-600'}`}>{capacityPct}%</span>
                                                    </div>
                                                </div>
                                                
                                                <div className="text-[10px] font-semibold text-slate-500">Max: <span className="font-bold text-slate-800">{Math.round(maxTension).toLocaleString()} N</span></div>
                                                <div className="text-[9px] font-medium text-slate-400">Limit: {Math.round(boltCapacityN).toLocaleString()} N</div>
                                            </div>
                                            
                                            {/* Right: Top 5 Table */}
                                            <div className="w-[70%] flex flex-col">
                                                <div className="rounded-lg border border-slate-200 bg-white flex flex-col overflow-hidden">
                                                    <table className="w-full text-left text-[10px]">
                                                        <thead className="bg-slate-100 text-slate-600 font-bold border-b border-slate-200">
                                                            <tr>
                                                                <th className="p-2">Rank</th>
                                                                <th className="p-2">Pos (X, Z)</th>
                                                                <th className="p-2 text-right">Tension (N)</th>
                                                                <th className="p-2 text-center">Status</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody className="divide-y divide-slate-100">
                                                            {top5Bolts.map((b, i) => {
                                                                const tension = Math.max(0, b.netTensionN);
                                                                const safe = tension <= boltCapacityN;
                                                                return (
                                                                    <tr key={i} className="hover:bg-slate-50 transition-colors">
                                                                        <td className="p-2 font-bold text-slate-400">#{i+1}</td>
                                                                        <td className="p-2 text-slate-600 font-mono font-medium">({b.x.toFixed(2)}, {b.z.toFixed(2)})</td>
                                                                        <td className="p-2 text-right font-mono font-bold text-amber-600">{Math.round(tension).toLocaleString()}</td>
                                                                        <td className="p-2 text-center">
                                                                            <span className={`px-1.5 py-0.5 rounded text-[8px] tracking-wider font-bold ${safe ? 'bg-emerald-100 text-emerald-700' : 'bg-red-100 text-red-700'}`}>{safe ? 'SAFE' : 'FAIL'}</span>
                                                                        </td>
                                                                    </tr>
                                                                )
                                                            })}
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>

                                        {/* Bottom: Area Chart for Tension Profile */}
                                        <div className="flex-1 bg-slate-50 rounded-xl border border-slate-100 p-3 flex flex-col min-h-0 print:break-inside-avoid">
                                            <div className="flex justify-between items-center mb-1">
                                                <h4 className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Tension Profile (Top 20 Bolts)</h4>
                                            </div>
                                            <div className="flex-1 min-h-0">
                                                <ResponsiveContainer width="100%" height="100%">
                                                    <AreaChart data={boltData} margin={{ top: 15, right: 10, left: 0, bottom: 0 }}>
                                                        <defs>
                                                            <linearGradient id="colorTension" x1="0" y1="0" x2="0" y2="1">
                                                                <stop offset="5%" stopColor="#f59e0b" stopOpacity={0.8}/>
                                                                <stop offset="95%" stopColor="#f59e0b" stopOpacity={0.1}/>
                                                            </linearGradient>
                                                            <linearGradient id="colorShear" x1="0" y1="0" x2="0" y2="1">
                                                                <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.5}/>
                                                                <stop offset="95%" stopColor="#3b82f6" stopOpacity={0.05}/>
                                                            </linearGradient>
                                                        </defs>
                                                        <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
                                                        <XAxis dataKey="name" tick={{fontSize: 9, fill: '#94a3b8'}} tickLine={false} axisLine={false} />
                                                        <YAxis tick={{fontSize: 9, fill: '#94a3b8'}} tickLine={false} axisLine={false} tickFormatter={(val) => `${val/1000}k`} />
                                                        <Tooltip 
                                                            contentStyle={{borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)'}} 
                                                            itemStyle={{fontSize: '10px', fontWeight: 'bold'}} 
                                                            labelStyle={{fontSize: '10px', color: '#64748b'}} 
                                                        />
                                                        <Legend verticalAlign="top" height={20} iconType="circle" wrapperStyle={{fontSize: '10px', fontWeight: 'bold', paddingTop: '5px'}} />
                                                        <ReferenceLine y={boltCapacityN} stroke="#ef4444" strokeDasharray="3 3" label={{ position: 'insideTopLeft', value: 'Capacity Limit', fill: '#ef4444', fontSize: 9, fontWeight: 'bold' }} />
                                                        <Area type="monotone" dataKey="shear" stroke="#3b82f6" strokeWidth={2} fillOpacity={1} fill="url(#colorShear)" name="Shear (N)" />
                                                        <Area type="monotone" dataKey="tension" stroke="#f59e0b" strokeWidth={2} fillOpacity={1} fill="url(#colorTension)" name="Tension (N)" />
                                                    </AreaChart>
                                                </ResponsiveContainer>
                                            </div>
                                        </div>
                                    </div>
                                );
                            })()}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
